name = "anon-board"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "AIC_LECTURE"
id = "6f97a7b0d05743299f3ef37954c29457"

# 任意: 管理用トークン（DELETE 用）。
# 本番は Dashboard の環境変数から設定してください。
[vars]
ADMIN_TOKEN = "change-me"

